Feature/#3 feat main activity
HapdongSeminarApp4/Android_Korail pull request #5
Opened 2022-11-19 14:48 UTC by 0zlrlo

## 관련 이슈
- #3 [ui] activity_main/xml 구현
## 작업한 내용
- 메인 액티비티 xml 구현

## PR 포인트
-

2022-11-21 07:00 UTC, wkdyujin reviewed
액티비티에 네비게이션 바가 있는거구, 그 위에 승차권 예매, 승차권 확인 같은 프래그먼트가 올라가는 거라서 activity_main에 추가한 코드는 전부 fragment_train으로 옮겨줘야해 !!

여기저기 고민한 흔적이 많이 보인다..! 고생 많았어~!!

2022-11-21 07:00 UTC, wkdyujin commented on app/src/main/res/layout/activity_main.xml
> +        <!--        8. 왕복 버튼 이미지 추출-->
1. 맞아~! px는 절대적 단위라서 기기마다 다른 비율을 조절해주기 위해 dp를 써
2. 반올림하면 될 것 같아
3. 이건 무슨 말이지?!
4. textAppearance 사용하면 될거야`android:textAppearance="@style/H1"` 요런 식으로!
5. 40 맞는데? 잘 썼네~!
6. 벡터 xml..?!
7. 뷰로 감싸도 되고, drawable~(예.drawablestart) 속성을 이용할 수도 있고 여러가지 방법이 있을 것 같아
8. 피그마에서 svg로 export해서 vector asset으로 넣어주면 돼!

2022-11-21 07:00 UTC, wkdyujin commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.KorailAOS" parent="Theme.AppCompat.DayNight.NoActionBar">
버튼 색상이 background로 안 바뀌어서 MaterialComponents를 AppCompat로 바꾼 것 같은데, background 대신 backgroundTint 쓰면 색깔 바꿀 수 있어! 이 부분은 아마(?) 고치면 안 될거야

2022-11-21 07:22 UTC, 0zlrlo commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.KorailAOS" parent="Theme.AppCompat.DayNight.NoActionBar">
엇 아 이게 drawer 만들 때 변경했던 부분인 거 같은데.. 다시 바꿨어:)

2022-11-21 07:27 UTC, 0zlrlo commented on app/src/main/res/layout/activity_main.xml
> +        <!--        8. 왕복 버튼 이미지 추출-->
4. 폰트 적용 android:fontFamily 이 속성을 활용했는데 이것과 차이점이 있는 건가?
8. 추출하려고 했는데 오른쪽 화살표랑 왼쪽 화살표가 함께 되어 있는 이미지가 추출되어야 하는데 따로 되더라구,,이건 디자인 담당하시는 분께 말씀을 드려야 하는 건가?

2022-11-21 07:27 UTC, 0zlrlo commented
아아 어제 밤에 main activity가 아니라 fragment train에서 짜야 한다는 것을 pr 올리고 나서 깨달았어..고마워!!!

2022-11-21 07:46 UTC, wkdyujin commented on app/src/main/res/layout/activity_main.xml
> +        <!--        8. 왕복 버튼 이미지 추출-->
4. 글씨 크기, 폰트 같은 속성을 다 저장해둔 거라 번거롭게 여러 속성 만들 필요가 없어~!
5. component2 > return 확인해봐 !!

2022-11-21 07:51 UTC, 0zlrlo commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.KorailAOS" parent="Theme.AppCompat.DayNight.NoActionBar">
바꾸면 안되는 건 알았는데..! 내가 다시 MaterialComponents 이걸로 바꾸니까 색깔 적용이 안되는 게 안되더라구,.음,,

2022-11-21 08:05 UTC, 0zlrlo commented on app/src/main/res/layout/activity_main.xml
> +        <!--        8. 왕복 버튼 이미지 추출-->
옹 됐어! 고마워:)

2022-11-21 08:09 UTC, wkdyujin commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.KorailAOS" parent="Theme.AppCompat.DayNight.NoActionBar">
background를 backgroundTint로 수정해도 안 될까? 로컬에서 변경해보니까 색 바뀌는데..!

2022-11-21 08:22 UTC, 0zlrlo commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.KorailAOS" parent="Theme.AppCompat.DayNight.NoActionBar">
음,,언니 갠톡 보냈어! 확인 한 번만 부탁할게ㅠㅠ

2022-11-21 08:40 UTC, 0zlrlo commented on app/src/main/res/values/themes.xml
> +    <style name="Theme.KorailAOS" parent="Theme.AppCompat.DayNight.NoActionBar">
MaterialComponents 이걸로 하면 button에 이미지가 안 보입니다..

2022-11-21 09:47 UTC, KWY0218 requested changes
1. xml 에서도 윈도우 기준이지만 crtl + alt + L 로 정렬이 가능합니다.
    중간 중간에 적용해주세요 !
2. string 리소스를 활용해서 text 작성해주세요 !
3. text appearance 를 이용해 주세요 !
![image](https://user-images.githubusercontent.com/82709044/203018063-cb7f1b15-2032-4bd9-a767-7bc7443a0835.png)
    폰트 알고 싶은 text 클릭 후 `inspect` 에서 확인 가능합니다 !
    2번으로 마우스를 옮기면 텍스트를 복사할 수 있어서 타이핑 안해도 됩니다 !
    3번에서 `h1_sb_25pt` 라고 되어 있으면 `textAppearance = @style/H1` 이런식으로 하면 됩니다 !

2022-11-24 13:24 UTC, KWY0218 requested changes
remote 패키지 내에 있는 파일들이 왜 있는지 궁금합니다...!

2022-11-24 13:24 UTC, KWY0218 commented on app/src/main/java/com/example/korail_aos/remote/ResponseMainDTO.kt
> +)
세미나 과제 코드 같아 보이는데 이 코드를 가져온 이유가 있을까요....?

2022-11-24 13:24 UTC, KWY0218 commented on app/build.gradle
> +    implementation("com.squareup.okhttp3:logging-interceptor")
이미 추가되어 있는 디펜던시 입니다..!

2022-11-24 13:24 UTC, KWY0218 commented on app/src/main/java/com/example/korail_aos/presentation/train/TrainFragment.kt
> +    lateinit var MainService: MainService
아직 서버 통신 로직이 develop에 머지가 안되어 있어서 현재 브랜치에선 사용할 수 없습니다..!
제 피알이 develop 브랜치가 머지된 후 풀을 받은 후에 사용할 수 있습니다

2022-11-24 13:31 UTC, 0zlrlo commented on app/build.gradle
> +    implementation("com.squareup.okhttp3:logging-interceptor")
넵 삭제하였습니다

2022-11-24 13:31 UTC, 0zlrlo commented on app/src/main/java/com/example/korail_aos/presentation/train/TrainFragment.kt
> +    lateinit var MainService: MainService
네네! 확인하였습니다

2022-11-24 13:31 UTC, 0zlrlo commented on app/src/main/java/com/example/korail_aos/remote/ResponseMainDTO.kt
> +)
세미나때 하던 거 활용해서 이것저것 해보려고 가져왔어요..! 지금은 다시 저희 걸로 수정한 상태입니다

2022-11-25 15:49 UTC, merged